import type { Metadata, Viewport } from 'next'
import { Inter, Space_Grotesk } from 'next/font/google'
import { Providers } from './providers'
import { Toaster } from 'sonner'
import './globals.css'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
})

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  variable: '--font-space-grotesk',
  display: 'swap',
})

export const metadata: Metadata = {
  metadataBase: new URL(process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000'),
  title: {
    default: 'FX Gym | Transform Your Body, Elevate Your Mind',
    template: '%s | FX Gym',
  },
  description: 'Premium fitness experience with state-of-the-art equipment, expert trainers, and a community that pushes you further. Join FX Gym today.',
  keywords: ['gym', 'fitness', 'workout', 'personal training', 'group classes', 'strength training', 'cardio'],
  authors: [{ name: 'FX Gym' }],
  creator: 'FX Gym',
  publisher: 'FX Gym',
  robots: 'index, follow',
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: 'https://fxgym.com',
    siteName: 'FX Gym',
    title: 'FX Gym | Transform Your Body, Elevate Your Mind',
    description: 'Premium fitness experience with state-of-the-art equipment, expert trainers, and a community that pushes you further.',
    // Image is generated by src/app/opengraph-image.tsx (file convention)
  },
  twitter: {
    card: 'summary_large_image',
    title: 'FX Gym | Transform Your Body, Elevate Your Mind',
    description: 'Premium fitness experience with state-of-the-art equipment, expert trainers, and a community that pushes you further.',
    creator: '@fxgym',
  },
  verification: {
    google: 'google-site-verification-code',
  },
}

export const viewport: Viewport = {
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: '#0a0a0f' },
    { media: '(prefers-color-scheme: dark)', color: '#0a0a0f' },
  ],
  width: 'device-width',
  initialScale: 1,
  maximumScale: 5,
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${inter.variable} ${spaceGrotesk.variable}`}>
      {/* Fonts are self-hosted via next/font – no external font requests or preconnects needed. */}
      <body className="min-h-screen bg-gym-bg font-sans antialiased">
        <Providers>
          <Toaster position="top-right" theme="dark" className="bg-gym-surface border-gym-border" />
          <a
            href="#main-content"
            className="sr-only focus:not-sr-only focus:absolute focus:top-4 focus:left-4 z-50 px-4 py-2 bg-gym-primary text-gym-bg rounded-md"
          >
            Skip to main content
          </a>
          {children}
        </Providers>
      </body>
    </html>
  )
}